// Real deployed app/CDN/R2/DuckDB. Mutable APIs are fixed; explicit failures are injected per case.
const {chromium}=require('playwright');
const fs=require('fs'),assert=require('node:assert/strict');
const APP=process.env.FF_APP_URL||'https://fruitingforecast.com/',R2='https://data.hanksjunkdrawer.com/';
const report={app:APP,generatedAt:new Date().toISOString(),acceptance:[],failureModes:[],mobile:null,network:null};
function weather(lat,lon){let days=[],hours=[];for(let i=-30;i<=7;i++)days.push(new Date(Date.now()+i*86400000).toISOString().slice(0,10));for(let i=-720;i<=168;i++)hours.push(new Date(Date.now()+i*3600000).toISOString().slice(0,13)+':00');return {latitude:lat,longitude:lon,elevation:1200,timezone:'America/Denver',daily:{time:days,precipitation_sum:days.map(()=>1.5),temperature_2m_max:days.map(()=>22),temperature_2m_min:days.map(()=>9),et0_fao_evapotranspiration:days.map(()=>.15)},hourly:{time:hours,temperature_2m:hours.map(()=>15),relative_humidity_2m:hours.map(()=>70),dew_point_2m:hours.map(()=>8),precipitation:hours.map(()=>.04),soil_temperature_0cm:hours.map(()=>12),soil_moisture_0_to_1cm:hours.map(()=>.25),vapour_pressure_deficit:hours.map(()=>.5),wind_speed_10m:hours.map(()=>6)}}}
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 async function open(failure){const context=await browser.newContext({viewport:{width:1280,height:900}}),page=await context.newPage(),requests=[],errors=[],pageErrors=[],badResponses=[];
  page.on('request',r=>requests.push(r.url()));page.on('pageerror',e=>pageErrors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('response',r=>{if(r.status()>=400)badResponses.push({url:r.url(),status:r.status()})});await page.addInitScript(()=>window.__FF_TEST_FAST__=true);
  await page.route('https://api.open-meteo.com/v1/forecast**',r=>{if(failure==='weather')return r.fulfill({status:503,body:'deliberate weather failure'});let u=new URL(r.request().url()),lats=u.searchParams.get('latitude').split(',').map(Number),lons=u.searchParams.get('longitude').split(',').map(Number),rows=lats.map((lat,i)=>weather(lat,lons[i]));return r.fulfill({json:rows.length===1?rows[0]:rows})});
  await page.route('https://api.inaturalist.org/**',r=>failure==='observations'?r.fulfill({status:503,body:'{}'}):r.fulfill({json:{total_results:0,results:[]}}));
  if(failure==='manifest')await page.route('**/data/manifest.json**',r=>r.fulfill({status:503,body:'unavailable'}));
  if(failure==='access')await page.route(R2+'ap/**',r=>r.fulfill({status:503,body:'unavailable'}));
  await page.goto(APP,{waitUntil:'domcontentloaded',timeout:90000});await page.waitForFunction(()=>window.__FRUITING_FORECAST_TEST__,null,{timeout:90000});await page.locator('#radiusSelect').selectOption('10');await page.locator('#depthSelect').selectOption('quick');return {context,page,requests,errors,pageErrors,badResponses};
 }
 async function result(page){return page.evaluate(()=>{let s=__FRUITING_FORECAST_TEST__.getState(),a=s.analysis;return {profile:a?.biology.profileId,maturity:a?.biology.maturity,ranked:a?.ranked.map(x=>({species:x.speciesId,score:x.score})),filter:a?.filterState,gis:a?.gis,top:document.getElementById('topBet').textContent,observations:a?.observations,starts:(s.gis.properties||[]).filter(x=>x.suggestedStart).map(x=>({propertyId:x.id,start:x.suggestedStart})),status:document.getElementById('status').textContent}})}
 async function finish(page){await page.waitForFunction(()=>!document.getElementById('analyzeBtn').disabled&&/Analysis ready|Weather service failed/.test(document.getElementById('status').textContent),null,{timeout:180000});return result(page)}
 async function run(p,lat,lon,focus='best',species){await p.locator('#locationInput').fill(`${lat}, ${lon}`);await p.locator('#focusSelect').selectOption(focus);if(species)await p.locator('#speciesSelect').selectOption(species);await p.locator('#analyzeBtn').click();return finish(p)}
 const s=await open(),p=s.page;
 for(const [label,lat,lon,focus,species] of [['salida-best',38.5347,-105.9989,'best'],['salida-beginner',38.5347,-105.9989,'beginner'],['salida-specific',38.5347,-105.9989,'specific','morel'],['hardwood',38.3553,-87.5675,'best'],['sparse',33.5,-112.1,'best'],['excluded-border',49.5,-110.5,'best'],['adjacent-us-border',48.9,-110.5,'best']]){
  let before=s.requests.filter(x=>x.endsWith('.parquet')).length,r=await run(p,lat,lon,focus,species);
  if(label==='salida-best')assert.equal(r.ranked.length,4);
  if(label==='salida-beginner'){assert.equal(r.filter.emptyResultReason,'FILTER_NO_MATCH');await p.locator('[data-focus-recovery="best"]').click();r.recovery=await finish(p);assert.equal(r.recovery.ranked.length,4)}
  if(label==='salida-specific')assert.equal(r.filter.emptyResultReason,'SPECIES_NOT_MODELED');
  if(label==='hardwood'){assert.equal(r.profile,'hardwood');assert.ok(r.starts.length>0)}
  if(label==='sparse'){assert.equal(r.maturity,'MODELED_SPARSE');assert.equal(r.ranked.length,0)}
  if(label==='excluded-border'){assert.equal(r.gis.tiles.length,0);assert.equal(s.requests.filter(x=>x.endsWith('.parquet')).length,before)}else assert.equal(r.gis.status,'enhanced');
  for(const {propertyId,start:a} of r.starts){assert.equal(a.startEligible,true);assert.ok(!a.restriction);assert.ok(['HIGH','MEDIUM'].includes(a.evidenceGrade));assert.match(a.accessId,/^osm:(node|way|relation):\d+$/);assert.ok(Number.isFinite(a.lat)&&Number.isFinite(a.lon));assert.ok(a.lat>=-90&&a.lat<=90&&a.lon>=-180&&a.lon<=180);assert.ok(a.source);assert.match(a.sourceUrl,/^https:\/\/(www\.)?(osm\.org|openstreetmap\.org)\/(node|way|relation)\/\d+$/);assert.ok(a.propertyId===propertyId||(a.propertyIds||[]).includes(propertyId))}
  report.acceptance.push({label,...r});console.log(label,'PASS');
 }
 // Mobile interactions on the real domain, including recovery and property details.
 await p.setViewportSize({width:390,height:844});await run(p,38.5347,-105.9989,'beginner');await p.locator('[data-focus-recovery="best"]').click();await finish(p);assert.equal(await p.locator('#focusSelect').inputValue(),'best');
 await run(p,38.3553,-87.5675);await p.locator('[data-property]').first().click();assert.ok((await p.locator('#detailContent').innerText()).length>20);let propertyDetails=true;
 await p.locator('#aboutTab').click();assert.ok(await p.locator('#aboutView').isVisible());await p.locator('#forecastTab').click();await p.locator('#settingsBtn').click();await p.locator('#settingsDialog').waitFor({state:'visible'});assert.ok(await p.locator('#settingsDialog').isVisible());await p.locator('[data-close="settingsDialog"]').click();
 report.mobile=await p.evaluate(()=>({width:innerWidth,horizontalOverflow:document.documentElement.scrollWidth-document.documentElement.clientWidth,mapHeight:document.getElementById('map').getBoundingClientRect().height,locationVisible:!!document.getElementById('locationInput').offsetParent,focusVisible:!!document.getElementById('focusSelect').offsetParent}));Object.assign(report.mobile,{filterRecovery:true,propertyDetails,about:true,settings:true});assert.equal(report.mobile.horizontalOverflow,0);assert.ok(report.mobile.mapHeight>100);
 // Real verified asset, then failed refresh (cache retained), then uncached failure.
 const asset=await p.evaluate(()=>__FRUITING_FORECAST_TEST__.getState().gis.manifest.tiles.find(t=>t.id==='n38_w106').habitat);
 const original=await p.evaluate(async a=>new Uint8Array(await __FRUITING_FORECAST_CACHE_TEST__.gisAssetBytes('domain-cache-canary',a,false)).length,asset);assert.equal(original,asset.bytes);
 await p.route(R2+asset.url,r=>r.fulfill({status:503,body:'deliberate parquet failure'}));
 const fallback=await p.evaluate(async a=>{let t=__FRUITING_FORECAST_CACHE_TEST__,bytes=await t.gisAssetBytes('domain-cache-canary',a,true),uncached;try{await t.gisAssetBytes('domain-uncached',a,false)}catch(e){uncached=e.message}return {bytes:bytes.byteLength,uncached}},asset);assert.equal(fallback.bytes,asset.bytes);assert.match(fallback.uncached,/HTTP 503/);report.failureModes.push({name:'parquet-verified-cache-and-uncached',passed:true,...fallback});
 assert.equal(s.requests.filter(u=>u.includes('openrouter.ai')).length,0);report.failureModes.push({name:'OpenRouter absent',passed:true,requests:0});
 const origins=[...new Set(s.requests.filter(u=>/^https?:/.test(u)).map(u=>new URL(u).origin))].sort();const allowed=[new URL(APP).origin,new URL(R2).origin,'https://unpkg.com','https://cdn.jsdelivr.net','https://extensions.duckdb.org','https://tile.openstreetmap.org','https://api.open-meteo.com','https://api.inaturalist.org'];
 const unexpected=origins.filter(x=>!allowed.includes(x));assert.deepEqual(unexpected,[]);assert.deepEqual(s.pageErrors,[]);
 const credentialUrls=s.requests.filter(u=>/^https?:/.test(u)&&(/[?&](?:key|api_key|token|access_token)=/i.test(u)||new URL(u).username));assert.deepEqual(credentialUrls,[]);
 report.network={origins,unexpected,credentialUrls,parquetOrigins:[...new Set(s.requests.filter(u=>u.endsWith('.parquet')).map(u=>new URL(u).origin))],manifestRequests:s.requests.filter(u=>u.includes('/manifest.json')),pageErrors:s.pageErrors,consoleErrors:s.errors,expectedInjectedResponses:s.badResponses};assert.deepEqual(report.network.parquetOrigins,[new URL(R2).origin]);assert.ok(s.badResponses.every(x=>x.url===R2+asset.url&&x.status===503));await s.context.close();
 for(const failure of ['manifest','weather','observations','access']){const f=await open(failure),r=await run(f.page,38.5347,-105.9989);if(failure==='weather'){assert.match(r.status,/Weather service failed/);assert.ok(!r.ranked)}else{assert.ok(r.ranked.length);if(failure==='manifest'){assert.equal(r.gis.status,'unavailable');assert.equal(r.gis.tiles.length,0)}if(failure==='observations'){assert.ok(Object.values(r.observations).every(o=>o.available===false))}if(failure==='access'){assert.equal(r.gis.accessPointCount,0);assert.equal(r.starts.length,0);assert.equal(r.gis.status,'enhanced')}}assert.deepEqual(f.pageErrors,[]);report.failureModes.push({name:failure,passed:true,status:r.status,gis:r.gis,observationsUnavailable:failure==='observations'?Object.values(r.observations).every(o=>o.available===false):undefined,consoleErrors:f.errors,pageErrors:f.pageErrors});console.log('failure',failure,'PASS');await f.context.close()}
 report.verdict='PASS';
}finally{fs.writeFileSync(process.argv[2]||'/tmp/ff-domain-qa.json',JSON.stringify(report,null,2)+'\n');await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
