// Run from repository root with its static server on localhost:8000.
// Both apps use real CDN/DuckDB/immutable R2; only mutable inputs/time are fixed.
const {chromium}=require('playwright');
const fs=require('fs'),assert=require('node:assert/strict');
const SOURCE=process.env.FF_SOURCE_URL||'https://hmarquardt.github.io/junkdrawer/fruiting-forecast.html';
const TARGET=process.env.FF_APP_URL||'http://localhost:8000/';
const FIXED='2026-09-20T12:00:00Z',R2='https://data.hanksjunkdrawer.com/';
const cases=[['salida-best',38.5347,-105.9989,'best','southernRockies'],['salida-beginner',38.5347,-105.9989,'beginner','southernRockies'],['hardwood',38.3553,-87.5675,'best','hardwood'],['pnw',47.6,-123.5,'best','pnw'],['sparse',33.5,-112.1,'best','warmDesert'],['border-excluded',49.5,-110.5,'best',null]];
function weather(lat,lon){let time=[],hours=[];for(let i=-30;i<=7;i++)time.push(new Date(Date.parse(FIXED)+i*86400000).toISOString().slice(0,10));for(let i=-720;i<=168;i++)hours.push(new Date(Date.parse(FIXED)+i*3600000).toISOString().slice(0,13)+':00');return {latitude:lat,longitude:lon,elevation:1200,timezone:'America/Denver',daily:{time,precipitation_sum:time.map(()=>1.5),temperature_2m_max:time.map(()=>22),temperature_2m_min:time.map(()=>9),et0_fao_evapotranspiration:time.map(()=>.15)},hourly:{time:hours,temperature_2m:hours.map(()=>15),relative_humidity_2m:hours.map(()=>70),dew_point_2m:hours.map(()=>8),precipitation:hours.map(()=>.04),soil_temperature_0cm:hours.map(()=>12),soil_moisture_0_to_1cm:hours.map(()=>.25),vapour_pressure_deficit:hours.map(()=>.5),wind_speed_10m:hours.map(()=>6)}}}
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});let output={fixedTime:FIXED,source:SOURCE,standalone:TARGET,mutableInputs:'Fixed weather and empty observations; fixed Date, real timers',runs:[]};try{
for(const url of [SOURCE,TARGET]){
 const context=await browser.newContext(),page=await context.newPage(),errors=[],failed=[],localErrors=[];let parquet=0;
 page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('requestfailed',r=>failed.push({url:r.url(),error:r.failure()}));page.on('response',r=>{if(r.url().startsWith(new URL(url).origin)&&r.status()>=400)localErrors.push({url:r.url(),status:r.status()})});page.on('request',r=>{if(r.url().startsWith(R2)&&r.url().endsWith('.parquet'))parquet++});
 await page.clock.setFixedTime(new Date(FIXED));await page.addInitScript(()=>window.__FF_TEST_FAST__=true);
 await page.route('**/api/analytics/**',r=>r.fulfill({status:204,body:''}));
 await page.route('https://api.open-meteo.com/v1/forecast**',r=>{let u=new URL(r.request().url()),lats=u.searchParams.get('latitude').split(',').map(Number),lons=u.searchParams.get('longitude').split(',').map(Number),rows=lats.map((lat,i)=>weather(lat,lons[i]));return r.fulfill({json:rows.length===1?rows[0]:rows})});
 await page.route('https://api.inaturalist.org/**',r=>r.fulfill({json:{total_results:0,results:[]}}));
 await page.goto(url,{waitUntil:'domcontentloaded',timeout:90000});await page.waitForFunction(()=>window.__FRUITING_FORECAST_TEST__,null,{timeout:90000});
 const deployment=await page.evaluate(async()=>{let m=await __FRUITING_FORECAST_TEST__.gisManifest(false);return {appVersion:document.querySelector('[data-deploy-version]').dataset.deployVersion,datasetVersion:m.datasetVersion,tiles:m.tiles.length}});assert.equal(deployment.datasetVersion,'content-db0f839a4352ef82');assert.equal(deployment.tiles,922);
 await page.locator('#radiusSelect').selectOption('10');await page.locator('#depthSelect').selectOption('quick');let results=[];
 async function finish(){await page.waitForFunction(()=>!document.getElementById('analyzeBtn').disabled&&/Analysis ready/.test(document.getElementById('status').textContent),null,{timeout:180000});return page.evaluate(()=>{let a=__FRUITING_FORECAST_TEST__.getState().analysis;return {profile:a.biology.profileId,maturity:a.biology.maturity,roster:a.speciesConfiguration.map(s=>s.id),ranked:a.ranked,zones:a.zones.map(z=>({id:z.id,scores:z.scores})),filterState:a.filterState,gis:a.gis,topText:document.getElementById('topBet').textContent.trim()}})}
 for(const [label,lat,lon,focus,profile] of cases){let before=parquet;await page.locator('#locationInput').fill(`${lat}, ${lon}`);await page.locator('#focusSelect').selectOption(focus);await page.locator('#analyzeBtn').click();let result=await finish();if(profile)assert.equal(result.profile,profile);if(label==='border-excluded'){assert.equal(parquet-before,0);assert.equal(result.gis.tiles.length,0)}if(label==='salida-beginner'){assert.equal(result.filterState.emptyResultReason,'FILTER_NO_MATCH');await page.locator('[data-focus-recovery="best"]').click();result.recovered=await finish();assert.equal(result.recovered.ranked.length,4)}if(label==='sparse')assert.equal(result.maturity,'MODELED_SPARSE');results.push({label,result});console.log(url,label,result.profile,result.ranked.length)}
 output.runs.push({url,deployment,results,parquetRequests:parquet,errors,failedRequests:failed,localErrors});await context.close();
}
assert.deepEqual(output.runs[0].results,output.runs[1].results);for(const r of output.runs){assert.deepEqual(r.errors,[]);assert.deepEqual(r.failedRequests.filter(x=>!x.url.includes('/api/analytics/')),[]);assert.deepEqual(r.localErrors,[]);assert.ok(r.parquetRequests>0)}output.parity=true;output.verdict='PASS';
}finally{fs.writeFileSync(process.argv[2]||'/tmp/ff-parity.json',JSON.stringify(output,null,2)+'\n');await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
